export const AUDIT_OUTCOMES = Object.freeze({
  PENDING: 'pending',
  SUCCESS: 'success',
  FAILED: 'failed',
});

export const AUDIT_OUTCOME_VALUES = Object.freeze(
  Object.values(AUDIT_OUTCOMES),
);

export const AUDIT_ENTITY_TYPES = Object.freeze({
  APPLICATION: 'application',
  APPLICATION_REVIEW: 'application_review',
  USER: 'user',
  MEMBERSHIP: 'membership',
  MEMBERSHIP_POLICY: 'membership_policy',
  CERTIFICATE: 'certificate',
  COURSE: 'course',
  COURSE_REVIEW: 'course_review',
  COURSE_DOCUMENT: 'course_document',
  COURSE_POLICY: 'course_policy',
  COURSE_CERTIFICATE: 'course_certificate',
  ARTICLE: 'article',
  ARTICLE_REVIEW: 'article_review',
  ARTICLE_CATEGORY: 'article_category',
  ARTICLE_TAG: 'article_tag',
  SITE_SETTING: 'site_setting',
  CONTENT_PAGE: 'content_page',
  EMAIL_TEMPLATE: 'email_template',
  CERTIFICATE_TEMPLATE: 'certificate_template',
  CONTACT_SUBMISSION: 'contact_submission',
  COMPLAINT: 'complaint',
  ROLE_DEFINITION: 'role_definition',
});

export const AUDIT_ENTITY_TYPE_VALUES = Object.freeze(
  Object.values(AUDIT_ENTITY_TYPES),
);

export const AUDIT_ACTIONS = Object.freeze({
  REVIEWER_ASSIGNED: 'reviewer.assigned',
  REVIEWER_REASSIGNED: 'reviewer.reassigned',
  REVIEWER_UNASSIGNED: 'reviewer.unassigned',
  REVIEW_CHECKLIST_UPDATED: 'review.checklist_updated',
  REVIEW_NOTE_INTERNAL_ADDED: 'review.note_internal_added',
  REVIEW_NOTE_APPLICANT_ADDED: 'review.note_applicant_added',
  REVIEW_PAYMENT_WAIVED: 'review.payment_waived',
  REVIEW_PAYMENT_WAIVER_REMOVED: 'review.payment_waiver_removed',
  APPLICATION_INFORMATION_REQUESTED: 'application.information_requested',
  APPLICATION_APPROVED: 'application.approved',
  APPLICATION_REJECTED: 'application.rejected',
  APPLICATION_SUSPENDED: 'application.suspended',
  APPLICATION_RESUBMITTED: 'application.resubmitted',
  MEMBERSHIP_POLICY_UPDATED: 'membership.policy_updated',
  MEMBERSHIP_ISSUED: 'membership.issued',
  MEMBERSHIP_RENEWED: 'membership.renewed',
  MEMBERSHIP_SUSPENDED: 'membership.suspended',
  MEMBERSHIP_REINSTATED: 'membership.reinstated',
  MEMBERSHIP_REVOKED: 'membership.revoked',
  CERTIFICATE_REVOKED: 'certificate.revoked',
  CERTIFICATE_REPLACED: 'certificate.replaced',
  COURSE_POLICY_UPDATED: 'course.policy_updated',
  COURSE_REVIEWER_ASSIGNED: 'course.reviewer_assigned',
  COURSE_CHECKLIST_UPDATED: 'course.checklist_updated',
  COURSE_NOTE_INTERNAL_ADDED: 'course.note_internal_added',
  COURSE_NOTE_PROVIDER_ADDED: 'course.note_provider_added',
  COURSE_INFORMATION_REQUESTED: 'course.information_requested',
  COURSE_DOCUMENT_REVIEWED: 'course.document_reviewed',
  COURSE_APPROVED: 'course.approved',
  COURSE_REJECTED: 'course.rejected',
  COURSE_SUSPENDED: 'course.suspended',
  COURSE_REINSTATED: 'course.reinstated',
  COURSE_REVOKED: 'course.revoked',
  ARTICLE_MODERATOR_ASSIGNED: 'article.moderator_assigned',
  ARTICLE_CHANGES_REQUESTED: 'article.changes_requested',
  ARTICLE_APPROVED: 'article.approved',
  ARTICLE_PUBLISHED: 'article.published',
  ARTICLE_REJECTED: 'article.rejected',
  ARTICLE_ARCHIVED: 'article.archived',
  ARTICLE_RESTORED: 'article.restored',
  ARTICLE_CATEGORY_CREATED: 'article.category_created',
  ARTICLE_CATEGORY_UPDATED: 'article.category_updated',
  ARTICLE_TAG_CREATED: 'article.tag_created',
  ARTICLE_TAG_UPDATED: 'article.tag_updated',
  SITE_SETTING_UPDATED: 'site.setting_updated',
  CONTENT_PAGE_CREATED: 'content.page_created',
  CONTENT_PAGE_UPDATED: 'content.page_updated',
  EMAIL_TEMPLATE_CREATED: 'template.email_created',
  EMAIL_TEMPLATE_UPDATED: 'template.email_updated',
  CERTIFICATE_TEMPLATE_CREATED: 'template.certificate_created',
  CERTIFICATE_TEMPLATE_UPDATED: 'template.certificate_updated',
  SUPPORT_SUBMISSION_UPDATED: 'support.submission_updated',
  COMPLAINT_UPDATED: 'support.complaint_updated',
  USER_ADMIN_UPDATED: 'user.admin_updated',
  ROLE_DEFINITION_UPDATED: 'role.definition_updated',
});

export const AUDIT_ACTION_VALUES = Object.freeze(Object.values(AUDIT_ACTIONS));
